events {}

http {
  upstream harbor_portal {
    server harbor-portal:8080;
  }

  upstream harbor_core {
    server harbor-core:8080;
  }

  upstream harbor_registry {
    server harbor-registry:5000;
  }

  server {
    listen 8080;
    client_max_body_size 0;

    location / {
      proxy_pass http://harbor_portal;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
      proxy_pass http://harbor_core;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /service/ {
      proxy_pass http://harbor_core;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /v2/ {
      proxy_pass http://harbor_registry;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Docker-Distribution-Api-Version registry/2.0;
    }
  }
}
