appname = Harbor
runmode = dev
enablegzip = true
httpport = 8080
harbor_admin_password = Harbor12345
auth_mode = db_auth
self_registration = off
project_creation_restriction = everyone
token_expiration = 30
ext_endpoint = http://localhost:8081
